name: "✨ Feature"
description: Suggest a feature or enhancement to improve Cervello.
body:
  - type: markdown
    attributes:
      value: |
        Have a question? 👉 [Start a new discussion](https://github.com/iotblue/Cervello-Support/discussions)
  - type: textarea
    id: feature
    attributes:
      label: What would you like?
      description: A clear description of the feature or enhancement wanted in Cervello.
      placeholder: I'd like to be able to...
  - type: textarea
    id: product
     choice:
       type: choice
       description: Make a choice
       options:
       - foo
       - bar
       - baz
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why is this needed?
      description: Please provide a clear description of why this would be useful to you. 
      placeholder: I want this because...
  - type: textarea
    id: other
    attributes:
      label: Further Information
      placeholder: Any other details?
